name: CI CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
            
      - name: Cache Maven package
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.repository }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ github.repository }}-

      - name: Maven Package
        run: mvn clean package --no-transfer-progress

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/discovery:latest
          docker build --build-arg JAR_FILE=$JAR_FILE -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    needs: package  
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare directory
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            mkdir -p ~/docker-microservices/discovery
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > ~/docker-microservices/discovery/.env
  
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          source: "docker-compose.yml"
          target: "~/docker-microservices/discovery/"
  
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: | 
            cd ~/docker-microservices/discovery
            docker stack deploy -c docker-compose.yml discovery



