name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Package
        run: mvn clean package --no-transfer-progress

      - name: Copy artifact locally
        run: cp target/*.jar /tmp/built-discovery.jar

  docker:
    needs: package
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy artifact from package job
        run: cp /tmp/built-discovery.jar .

      - name: Build & Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/docker-microservices:discovery
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare directory
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            mkdir -p ~/docker-microservices/discovery
            
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          source: "docker-compose.yml"
          target: "~/docker-microservices/discovery/"
  
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          script: |        
            docker pull ${{ secrets.DOCKER_USERNAME }}/docker-microservices:discovery
            docker-compose -f ~/devops-ci-cd-github-actions/docker-compose.yml down
            docker-compose -f ~/devops-ci-cd-github-actions/docker-compose.yml up -d
